version: "3"
services:
  web:
    build: .
    ports: 
    - 80:80
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: aps
  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    depends_on:
    - mongo 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: aps